spring.datasource.url=jdbc:postgresql://dpg-d7unidhkh4rs73acf7og-a.singapore-postgres.render.com:5432/eventdb_kkys

spring.datasource.username=eventuser

spring.datasource.password=XCp6UfNu9o4utJpSeCYaYg6CU3EQgXii

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}